# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule:
    - cron:  '*/30 * * * *'    # 国际标准时间22点（北京时间早上6点发） 
  push:
    branches:    
      - master
permissions:
  actions: write
  checks:  write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
        

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install The Environment
      run: |
        pip3 install requests
        pip3 install feedparser
    - name: Get The  secrets
      env:
        USER: ${{ secrets.USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
        HOST: ${{ secrets.HOST }}
      run: |
           python ./src/GetEnv.py
    - name: Run The Task
      run: |
        python ./src/setup.py
        python ./src/WeiBo.py
        python ./src/Bing.py

    - name: Make changes and commit
      run: |
        echo $(date) >> file.txt
        git config --global user.email "2563043733@qq.com"
        git config --global user.name "ilikui"
        git add file.txt
        git commit -m "Add new line to file"
        git status
    - name: Commit changes
      run: |
          git diff 
          git add .
          git config --global user.email "2563043733@qq.com"
          git config --global user.name "ilikui"
          git commit -m "commit "
          git push
        # if [$? -eq 1 ]; then
        #   echo "Will Push"
        #   git add .
        #   git config --global user.email "2563043733@qq.com"
        #   git config --global user.name "ilikui"
        #   git commit -m "commit "
        #   git push
        # else
        #     echo  "NO Changes"
        # fi
