name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:    
      - master
  workflow_dispatch:
permissions:
  actions: write
  checks:  write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: ./assets/github-contribution-grid-snake.gif
          svg_out_path: ./assets/github-contribution-grid-snake.svg

      - name: Make changes and commit
        run: |
          echo $(date) >> Snake.txt
          git config --global user.email "2563043733@qq.com"
          git config --global user.name "ilikui"
          git add file.txt
          git commit -m "Add new line to file"
          git status
      - name: Commit changes
        run: |
            git diff 
            git add .
            git config --global user.email "2563043733@qq.com"
            git config --global user.name "ilikui"
            git commit -m "commit "
            git push